### ISSUE TITLE
Space ripper recipe not working

### ISSUE THREAD

**Issue by ombravera** [Dunkmania101/SpatialHarvesters#1]
Playing on forge 32.0.107
Minecraft 1.16.1

**Comment by Dunkmania101** [comment]
Which version of the mod are you using?
I noticed that issue in an earlier version, it was happening because the output for the recipe was set to the chunk loader.
It should have been fixed in V0.1.1 (Latest is V0.1.2)

**Comment by ombravera** [comment]
I am using 1.2

**Comment by Dunkmania101** [comment]
Found it! The same issue seems to have crept back in, probably while copying files. One moment, please (plus however long it'll take Curseforge to make the file available)...

**Comment by ombravera** [comment]
Perfect thank you

**Comment by Dunkmania101** [comment]
:)

**Comment by ombravera** [comment]
It seems to be working properly again thank you
