### ISSUE TITLE
Feature/enhancement for the mob harvester

### ISSUE THREAD

**Issue by Taccio33** [Dunkmania101/SpatialHarvesters#10]
Hi! So thanks to you I understood that the mob harvester needs to be bounded and so I got two ideas that (only if they are possible) I would like to give to you:
1. Have a way to signify that a key is bounded correctly (maybe the enchantment glow or even the a tag/text with the bounded mob)

2. Testing with the Wither and the Ender Dragon (because: why not) I've noticed that the Wither seems to bind, but the nether star is not a drop (I think vanilla is weird about that, it just checks for a wither death and spawns a nether star), and the ender dragon doesn't bound at all so... maybe you could add them as a custom? Ideas for the ender dragon loot: dragon egg, elytra andr dragon's breath, all items that some mods use as a very high end crafting and don't have a renewable source

Thank you very much in advance, love the mod!

**Comment by Dunkmania101** [comment]
There's a status message that shows when the Mob Key is bound to something or is used on a harvester. As for the bosses, the machine is already so pathetically broken that it doesn't even seem to do anything for some people. I'll probably try that later if I ever get the thing to work reliably in the first place. Thanks for pointing that out though, I had no idea. There is another mod called "Woot" that has something similar that actually works as intended and supports bosses.

**Comment by Taccio33** [comment]
Ah yes, woot was exactly the mod I was thinking about. I followed it's early stages and it actually had the same problem with both of them, so (to my knowledge) the mod author first made an exception for them (crafting a core instead of bounding for the dragon, adding the nether star as an additional loot table for the wither), and then fixed it using something else (really don't know what). Thanks for the patience and thanks again !
