### ISSUE TITLE
Mob Harvester: Blaze

### ISSUE THREAD

**Issue by burshaz** [Dunkmania101/SpatialHarvesters#14]
The Mob Harvester doesn't produce anything when set to Blaze

MC 1.16.3
Forge 34.1.19
spatialharvesters_1_16_3-0.7.12

Added for power:
Mekanism-1.16.3-10.0.11

**Comment by Dunkmania101** [comment]
I get the feeling the way I was determining the drops was a little broken. I think I know of an alternative that should work a little better, I'll update with that in place. Thanks!

**Comment by Dunkmania101** [comment]
I'm about to publish 0.7.13 which should hopefully resolve this. I'll close this now, thanks!
