### ISSUE TITLE
Please tidy up the config file.

### ISSUE THREAD

**Issue by llssc** [Dunkmania101/SpatialHarvesters#15]
I edited the config file to make the mod experience more reasonable (by my standard), grouping each entries that were not sorted at all.

I tried to edit it once more after testing out the values and saw that the config file has been unsorted again.
Please tidy it up.

PS. Some entries for custom block entries still say "Soil" although the lines below them are for different entries.

**Comment by Dunkmania101** [comment]
It used to be organized, but then I encountered some issues and eventually gave up and just put everything on the same level. I'll see if I can get it to work. As for the names, I'll look at that too. If it's already correct, you might need to delete the file and let it regenerate.

**Comment by Dunkmania101** [comment]
Done!

**Comment by Dunkmania101** [comment]
Just so you know, I have published the improved version with 0.7.20, Curseforge is just taking a really long time to approve it.
