### ISSUE TITLE
If you can, make the number type of max energy storage and/or cost per operation to long

### ISSUE THREAD

**Issue by llssc** [Dunkmania101/SpatialHarvesters#16]
The game will crash if I try to set the cost to 214,748,365 (1/10th of max int, rounded), so I assume it is because it can't handle the overflow from trying to multiply it by 10 and store it as max energy storage.

Swap the data type/s so that it won't crash for the players like me who are trying to set astronomical numbers as cost.

**Comment by Dunkmania101** [comment]
Unfortunately, the Forge energy system seems to require integers. I'll lower the maximum to prevent those crashes, though. Sorry!
