### ISSUE TITLE
SpatialHarvesters Forge 0.10.5 server crash

### ISSUE THREAD

**Issue by Deiwos** [Dunkmania101/SpatialHarvesters#29]
Hello. I just updated Spatial Harvesters from 0.10.3 to 0.10.5 for my pack/server, and as I approached the base of someone who was using a Spatial Harvester setup, the server crashed with the following crash log. Attempting to log in again after restarting the server caused the same error, and rolling back to 0.10.3 fixed it.

https://pastebin.com/pTZfs2ZC

**Comment by Dunkmania101** [comment]
Looks like I was checking if the tags were valid in a way that didn't work for some reason.
I (hopefully) fixed it in 0.10.6, so I'll close this for now. Feel free to reopen if it still crashes!

**Comment by MSandro** [comment]
Thank you very much. 0.10.5a is now working very well!
