### ISSUE TITLE
[Fabric] Heat Generators Forget they are Heat Generators

### ISSUE THREAD

**Issue by milkev** [Dunkmania101/SpatialHarvesters#31]
upon leaving/rejoining a world, heat generators stop working until they are broken and replaced. They also seem to forget what machine they are, and output unrelated information while in this state.
Tested on fabric 1.16.5 with latest version of spatial harvesters and fabric, among other mods.
![2021-02-05_20 38 21](https://user-images.githubusercontent.com/22010128/107108021-44443780-67f2-11eb-8f6d-92caceef6a0c.png)

**Comment by Dunkmania101** [comment]
I had noticed they were stopping on world reload, but that's really weird! I'll try to figure it out, maybe knowing that they think they're different machines will help lead me to the problem.

**Comment by Dunkmania101** [comment]
Welp, found it :) See if you can spot the issue:
![image](https://user-images.githubusercontent.com/50186904/107108249-942bfa00-6804-11eb-9d86-d78f3bff3d66.png)


That's the wrong class! I'll fix that!

**Comment by Dunkmania101** [comment]
Done in 0.11.1!
