### ISSUE TITLE
[Fabric] Dark Mob Harvester does nothing?

### ISSUE THREAD

**Issue by MSandro** [Dunkmania101/SpatialHarvesters#35]
![image](https://user-images.githubusercontent.com/10937159/108117926-e8a16600-709d-11eb-8123-964fe6a937a9.png)
Hello, maybe I'm just too stupid to use the dark mob harvester, but it doesn't give any items. I used a weapon key but it doesn't work with it either. Do I have to pay attention to something in the Fabric version in contrast to the Forge version?
Or it can be that it does not work in combination with my Modpack (All Of Fabric 3 v2.6.6)

**Comment by Dunkmania101** [comment]
What does the Sneak-Right-Click (needs an empty hand for some reason) info about the harvester say? Is the energy going up? One of the only things I can think of right now is if that battery on top uses a different kind of energy than the Reborn kind.

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/108357938-61afd300-71ee-11eb-93ff-30e9039e6a3e.png)

the energy looks good, I use the Creative Solar Panel from TechReborn. Does it require to set a mob? but I can't use the Mob Key on it...

**Comment by Dunkmania101** [comment]
It should even work without a set weapon, simulating kills with an empty hand instead. I do see in that picture that there isn't a bound mob. You can't use the mob key on it because the dark mob harvester is supposed to set a new random mob automatically each cycle. Not sure what's happening, let me take a look...

**Comment by Dunkmania101** [comment]
Found it! In the Mob Key Item (and in a few other places), I was trying to get the registry name of the mob but was instead getting its translation key. For example, I might want "minecraft:pig" but was instead getting "entity.minecraft.pig". I'll release a fix in 0.11.5.

**Comment by Dunkmania101** [comment]
Done!

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/108497291-861db500-72ab-11eb-8cfd-aaad091896b6.png)

now it is selecting mobs but I don't get any output in the chest.

**Comment by MSandro** [comment]
I also noticed that the energy buffer was not emptied. When I destroyed the solar panel, the energy remained at 800,000. The phenomenon does not occur with the other harvesters.

**Comment by Dunkmania101** [comment]
I think it's actually happening to both mob harvesters. The dark one had two issues: not setting the mob and what I'm about to describe. They both seem to be failing to actually do anything with the mob once the string is set. I'll see if I can figure it out.

**Comment by Dunkmania101** [comment]
This one took way too long to figure out :/

I eventually found that the Entity mixin wasn't saving the dropped items to its NBT properly, which was where the harvester was reading them from. After a bunch of fiddling, I was able to work around it. I couldn't figure out how to save the items to the mob's NBT data from the mixin. However, I did manage to save them to a variable in the mixin itself and make the mob add it to the NBT data it sends. It seems to work now in 0.11.6, feel free to reopen if not.
