### ISSUE TITLE
All Botania Flowers Obtained From Bio Harvester

### ISSUE THREAD

**Issue by CuchilloMucho** [Dunkmania101/SpatialHarvesters#4]
All of the flowers from botania including the functional flowers and generating flowers etc come out of the bio harvester, mod version is 0.4.2

**Comment by Dunkmania101** [comment]
I disabled any Botania flowers from generating. That includes the basic mystical ones, but I guess that's still fair since the floral fertilizer approach is a thing. Thanks!
