### ISSUE TITLE
[Fabric] is the Specific Mob Harvester set to friendly creatures only?

### ISSUE THREAD

**Issue by MSandro** [Dunkmania101/SpatialHarvesters#40]
![image](https://user-images.githubusercontent.com/10937159/109066621-9a1f4780-76ed-11eb-9511-a3b3dec7f3ba.png)
![image](https://user-images.githubusercontent.com/10937159/109066664-aefbdb00-76ed-11eb-8a80-bd0dac5912b1.png)

Not sure why but I don't get blaze rods in my Specific Mob Harvester... no loot and no shards.
But if I set it to pigs, it outputs Raw Porkchop and Shards?
I can't find an config option for that.

**Comment by Dunkmania101** [comment]
It should be able to do any mob entity that isn't blacklisted in the config. I'll take a look.

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/109961679-8d50b400-7cea-11eb-9847-e6058210840b.png)
maybe it is because blaze rods are only droped if it was killed by a player?

**Comment by Dunkmania101** [comment]
That's true, although it shouldn't be the issue as the Mob Harvesters simulate player kills.

**Comment by MSandro** [comment]
Okay but I think it doesn't simulate player kills (correctly) ...
I've now added the mod "always-drop-loot" https://www.curseforge.com/minecraft/mc-mods/always-drop-loot
and now it outputs blaze rods and other items I've never seen before in my output chest.

**Comment by Dunkmania101** [comment]
It should be fixed in 0.11.7a. You were right, it wasn't stimulating the player kills correctly. 
One of the steps was to tell the mob entity that the fake player was its last attacker, but it was instead doing that for a new mob entity that never did anything else.
