### ISSUE TITLE
Harvesters dont save blacklisted resources on relog

### ISSUE THREAD

**Issue by AlexisBloodwood** [Dunkmania101/SpatialHarvesters#42]
So every time I log out, log back in, or crash then re-log, the harvesters forget their blacklists which result in me having to remake that list. I've gone ahead and made extra keys of the blocks I don't want them to make however I would like to have this fixed if it can be done.

![2021-03-04_12 32 48](https://user-images.githubusercontent.com/69871764/110013092-d4d54100-7ce6-11eb-83b2-94ca06ab611b.png)
![2021-03-04_12 37 11](https://user-images.githubusercontent.com/69871764/110013104-d7d03180-7ce6-11eb-890c-673673feb528.png)

**Comment by Dunkmania101** [comment]
It should be fixed in 0.11.7.
