### ISSUE TITLE
Updated to 0.11.7, Harvesters broke again

### ISSUE THREAD

**Issue by AlexisBloodwood** [Dunkmania101/SpatialHarvesters#43]
Recorded a short video of the issue, frustrating to say the least. TLDR: Blacklists dont work...

https://youtu.be/KXBzpBzbl9A

**Comment by Dunkmania101** [comment]
Was the harvester in the video using a blacklist set before the update? The old key might have saved incorrect values to it. Try clearing the blacklist (sneak-right-click) and re-creating it. I just tested it and it seems to work.

**Comment by AlexisBloodwood** [comment]
Making new keys as well seemed to fix it, though the change I made to the config to add in new ores still doesnt work. However that's for a different issue ticket.
