### ISSUE TITLE
Crash after altering config file

### ISSUE THREAD

**Issue by Pentasis** [Dunkmania101/SpatialHarvesters#45]
Version 0.11.7
Forge 36.1.0

I get this crashlog : https://paste.ee/p/CYTls

When I make 3 changes to the config file:

1. I remove glowstone from the custom ores list.
2. I set harvester_shard_chance = 0
3. I add the following blacklist: blacklist_ores = [["minecraft", "ancient_debris"], ["minecraft", "nether_gold_ore"], ["minecraft", "nether_quartz_ore"]]

Added my configfile here for reference: https://pastebin.com/QNFL5QyY

**Comment by Dunkmania101** [comment]
Found it! It's the second one. It was trying to find a random number between 0 and harvester_shard_chance, which has to be at least 1 (try picking an integer between 0 and 0, exclusive) or it'll crash, which it of course did. I'll do a release soon with a check in place to avoid that. Thanks for letting me know!

**Comment by Dunkmania101** [comment]
It should be fixed in 0.11.8. I'll close this now. Thanks for reporting!
