### ISSUE TITLE
Copper ore missing

### ISSUE THREAD

**Issue by Knito58** [Dunkmania101/SpatialHarvesters#46]
Thank you for the last update which suppressed all the ores who's mods are not installed. This reduced the output and the management of it a lot.
And thanks for glowstone in the config, didn't think of that.

Now the routerreborn copper_ore was missing but this one was fixed easily in the config file. Maybe you would put it into the config for those who won't dare to alter the config.

I went here to leave a star. And I'm the first one? Why? This mod is great.

In every new world its a primary goal to have spatial ore harvesters running.

Thanks alot.

**Comment by Dunkmania101** [comment]
Thanks for the star! I've never actually looked into what they mean, are they kind of like Youtube subscribers/likes?

As for the copper, it's probably not in the ores tag. I'll add it to the default config, is its registry name "routerreborn:copper_ore"?

**Comment by Knito58** [comment]
Yes and yes!
Thanks for caring.

**Comment by Dunkmania101** [comment]
Done! Should be available once Curseforge decides it's not malware :)
Thanks for thanking me for caring.
