### ISSUE TITLE
Version 0.11.12c is marked as compatible with 1.18.1 but doesn't load

### ISSUE THREAD

**Issue by DiogoHSS** [Dunkmania101/SpatialHarvesters#53]
When trying to play, fabric loader throws a warning that this version is compatible with 1.17.1 only, but on the curseforge page it is marked as compatible with 1.18 and 1.18.1

**Comment by Dunkmania101** [comment]
I saw a modpack that was using that version in 1.18 and assumed it would work. I'll remove those tags and release new jars at some point. Thanks for letting me know!
