### ISSUE TITLE
1.18.1 Adjacent Heat Generators not powering - 0.11.12d

### ISSUE THREAD

**Issue by mnsnownutt** [Dunkmania101/SpatialHarvesters#56]
I could not get any power via Tech Reborn (5.1.0), Modern Industrialization (1,0.4), Industrial Revolution (1.13.6) or Extra Generators (1.1.1) , so I tried heat generators.  They worked, until I tried putting multiple units next to each other.  

I opened a creative world to investigate and saw this odd behavior in the attached video.  EDIT - I also changed the speed on the heat generators, as you can see in the video, just to see if that would have an effect.

https://youtu.be/i4rTxH73nFc

**Comment by Dunkmania101** [comment]
Fixed in  0.11.13, see #55.
