### ISSUE TITLE
Weapon Enchantments?

### ISSUE THREAD

**Issue by zippoking** [Dunkmania101/SpatialHarvesters#66]
Hi, 

i am playing the Dreamcraft Modpack and i am using the specific mob harvester.
As you can see on the picture i have this Ender Gobber Greathammer with a lot of Enchantments. 

Inside the harvester i have a wither skeleton and as a weapon my hammer. 

![image](https://github.com/Dunkmania101/SpatialHarvesters/assets/18005338/12d4351a-694b-4012-b747-15694be149da)

![image](https://github.com/Dunkmania101/SpatialHarvesters/assets/18005338/d45559b0-c818-48c1-a00d-1c0027be2490)

My question is: 
Are the enchantments considered or does the harvester not use any enchentments (sharpness and looting) at all?
I have not seen a single drop of "wither rib" from the hearty trinkets mod as seen on the second screenshot.

Thx in advance
Best regards
Zippoking

**Comment by Dunkmania101** [comment]
It should. It simulates a player dealing the killing blow using an exact copy of the ItemStack that's set as the weapon, enchants and NBT data and all.
