### ISSUE TITLE
Heat Generator not making power

### ISSUE THREAD

**Issue by Blntswrd** [Dunkmania101/SpatialHarvesters#7]
I just updated to 1_16_2-0.4.16 and my heat generator stopped making power. I tried breaking it and replacing it as well as replacing the lava but it didn't fix it.

**Comment by Dunkmania101** [comment]
I think none of the machines were working. I had rearranged some code and made it so that they never counted ticks, meaning they'd keep thinking no time had passed to the next operation. It should be fixed in 0.4.17.
Thanks!
