### ISSUE TITLE
Crash on latest version

### ISSUE THREAD

**Issue by Taccio33** [Dunkmania101/SpatialHarvesters#8]

**Comment by Dunkmania101** [comment]
Hi, did you try V0.6.1 yet? If that one's still crashing, could you provide a list of all the mods you have and attach the debug.log file from when it happened? Thanks for your help with this issue, by the way.

**Comment by Dunkmania101** [comment]
Since there's someone else who probably has the same issue, I'll close this for now. Feel free to reopen if needed.

**Comment by Taccio33** [comment]
No prob, thanks for the quick replay (and yeah... I was asleep, sorry). Still testing to determin what could be the problem, but due to uni it will probably take me a bit of time.
